sudo: false
language: ruby
cache: bundler
rvm:
- 2.3.1
- 2.4.4
- 2.5.1
- ruby-head

gemfile:
  - gemfiles/Gemfile.activerecord-5.0.x
  - gemfiles/Gemfile.activerecord-5.1.x
  - gemfiles/Gemfile.activerecord-5.2.x

matrix:
  allow_failures:
    - rvm: ruby-head

env: DATABASE_URL=postgres://postgres@localhost/postgres_ext_test

before_script:
- psql -c 'create database postgres_ext_test;' -U postgres -h localhost
- bundle exec rake db:migrate

addons:
  postgresql: '9.6'
